FROM debian:latest

#COPY oj_web_build/apt/sources.list /etc/apt

RUN apt-get update && apt-get install -y --no-install-recommends build-essential git python-mysqldb mysql-client python-pip python-dev libjpeg-dev dos2unix nodejs nginx uwsgi vim curl gnupg2 python-setuptools && \
apt-get autoclean && rm -rf /var/lib/apt/lists/*
#npm
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs

RUN npm install -g bower

RUN git clone https://github.com/nthuoj/NTHUOJ_web.git && cd NTHUOJ_web && git checkout dev

COPY oj_web_build/NTHUOJ_web /NTHUOJ_web/

#https://github.com/bower/bower/issues/1752
RUN echo '{ "allow_root": true }' > /root/.bowerrc

#RUN apt-get install -y libmysqlclient-dev
#RUN apt-get install -y libmysqlclient18 zlib1g-dev

RUN curl -sL http://ftp.tw.debian.org/debian/pool/main/m/mysql-5.5/libmysqlclient-dev_5.5.55-0+deb8u1_amd64.deb > libmysqlclient-dev.deb
RUN curl -sL http://ftp.tw.debian.org/debian/pool/main/m/mysql-5.5/libmysqlclient18_5.5.55-0+deb8u1_amd64.deb > libmysqlclient18.deb
RUN curl -sL http://ftp.tw.debian.org/debian/pool/main/z/zlib/zlib1g-dev_1.2.8.dfsg-2+b1_amd64.deb > zlib1g-dev.deb
RUN apt-get install -f -y ./lib*.deb

RUN pip install -r /NTHUOJ_web/requirements.txt
RUN cd NTHUOJ_web && python install.py && python manage.py collectstatic --noinput
RUN ln -s /NTHUOJ_web/NTHUOJ_web_nginx.conf /etc/nginx/sites-enabled/

EXPOSE 8000

WORKDIR /NTHUOJ_web
VOLUME ["/var/nthuoj/","/NTHUOJ_web/media"]

#CMD ["sh", "start.sh"]
